baseURL = 'https://yif.fyi'
languageCode = 'zh-Hans'
title = 'Cyberspace of Yiffyi'

DefaultContentLanguage = 'zh-cn'
hasCJKLanguage = true

[module]
[[module.imports]]
path = 'github.com/CaiJimmy/hugo-theme-stack/v3'

[build]
noJSConfigInAssets = true

[imaging]
bgColor = '#ffffff'
# hint = 'photo'
quality = 90
resampleFilter = 'Lanczos'

[params.footer]
since = 2022

[params.sidebar]
emoji = 'ðŸŽ¶'

[params.widgets]
homepage = [
  { type = 'search' },
  { type = 'archives', params = { limit = 5 } },
  { type = 'categories', params = { limit = 10 } },
  { type = 'tag-cloud', params = { limit = 10 } },
]
page = [{ type = 'toc' }]

[params.article]
toc = true

[params.comments]
enabled = true
provider = 'giscus'

[params.comments.giscus]
repo = 'Yiffyi/Yiffyi'
repoID = 'R_kgDOIHqTEA'
category = 'Comments'
categoryID = 'DIC_kwDOIHqTEM4CRxDa'
mapping = 'pathname'
strict = 1
reactionsEnabled = 1
emitMetadata = 0
darkTheme = 'dark_dimmed'
inputPosition = 'top'
lang = 'zh-CN'

[params.colorScheme]
toggle = true
default = 'dark'
